# This file defines the principal settings for this project

# Definition of the grfs
REPO_NAME           ?= galician-railways

# This is the filename part common to the grf file, main source file and the tar name
BASE_FILENAME       ?= galician-railways

# Documentation files
DOC_FILES ?= dist/readme.txt dist/license.txt dist/changelog.txt

# Possible offset to NewGRF version. Increase by one, if a release
# branch is added to the repository
REPO_BRANCH_VERSION ?= 0

# Directory structure
SCRIPT_DIR          ?= scripts

# Uncomment in order to make use of gimp scripting. See the file
# for a description of the format
GFX_SCRIPT_LIST_FILES  := $(shell cat src/gfx/graphics_source_lists)

# If needed, declare the minimum NML requirements
# REQUIRED_NML_BRANCH  = 0.5
# MIN_NML_REVISION     = 0

# Install Directory
INSTALL_DIR := $(HOME)/.local/share/openttd/newgrf/

# Authors text
AUTHORS := pvillaverde (code, graphics), 
AUTHORS := ${AUTHORS}Ufiby(UReRMM-2 graphics), 